### ISSUE TITLE
Missing generations when using the Firefox browser

### ISSUE THREAD

**Issue by TheRealJPS** [magicsunday/webtrees-fan-chart#38]
I recognized a phenomenon that can best be explained with screenshots...

Firefox...
![grafik](https://user-images.githubusercontent.com/50000131/75385739-98575400-58e0-11ea-8bde-e50824c540ba.png)

Chrome, Opera, Edge...
![grafik](https://user-images.githubusercontent.com/50000131/75385984-26333f00-58e1-11ea-925a-e3db52ee105f.png)

**Comment by TheRealJPS** [comment]
It seems like this has to do with the "Number of inner circles", if the number is set to 1, the contents are displayed but not along the arc...
![grafik](https://user-images.githubusercontent.com/50000131/75386868-b6be4f00-58e2-11ea-9bb2-c4fc47c79441.png)

**Comment by magicsunday** [comment]
I did noticed that too, but thought this was just a problem of my firefox instance as it has some other odd behaviors too. Previously it was also working with the inner circles in firefox. I will take a look at it. Maybe I find something.

**Comment by magicsunday** [comment]
Could you please try the latest version from master branch?

**Comment by TheRealJPS** [comment]
It Works fine with Firefox Android version. I won't be able to try the Windows version before today's evening. But you can check it [here](https://ahnen.familie-stern.de/tree/stern/webtrees-fan-chart/I1)...

**Comment by Gunnar-GO** [comment]
it renders for me correctly, but at the moment i touch / move the graphic it passes away like the first image here. (FF 72.0.1)

If i change the size of the text, it is again there, and stays also if set back. 

As i unterstand the specification the order defines the z-index: https://www.w3.org/TR/SVG11/render.html#RenderingOrder 
Since the names are rendered first, the fields and colors later, maybe that would be an option to simply switch. 
//That also implies the question why it works on other browsers / worked before. Maybe just an error in SVG handling behavior in Firefox, but if it solveable by switch the rendering, why not ;)

**Comment by magicsunday** [comment]
@Gunnar-GO I'm confused. So do you still have the issue with the latest changes in master?

**Comment by Gunnar-GO** [comment]
nope, i test this at the moment and it solves the failure i described.

as i edited above, at the moment of typing, only the first 2 posts was to read, the othere posts and your hint for the new version was only refreshed / shown after my post. sry for confusion.

**Comment by jpretired** [comment]
I downloaded the last master version and tested it.
It is OK in firefox and chromium and opera. Everything displays as it should.
