### ISSUE TITLE
Underlines not aligned in inner circles

### ISSUE THREAD

**Issue by ekdahl** [magicsunday/webtrees-fan-chart#82]
See image below. Using version 5ee7605 (latest commit as of now).
![image](https://user-images.githubusercontent.com/2682230/169119311-0e0216c5-f57e-49ae-823c-e84c0bd42a78.png)

**Comment by ekdahl** [comment]
**Module version**
Version 2.3.0 not compatible with my webtrees version.
Version 2.4.0, here I see the odd lines.

**webtrees**
Using version 2.1.4 of webtrees (but used previous version when reporting the issue)

**Browser**
Same behavior in Chrome and Edge.
Chrome version 101.0.4951.67
Edge version 101.0.1210.53

**Sample site**
https://webtrees.ddns.net/tree/Ekdahl-Klahr/webtrees-fan-chart/1
Can be seen more clearly after zooming in.

**Comment by magicsunday** [comment]
This seems to be a bug in Chrome and therefore also in Edge since both are based on Chromium:
https://stackoverflow.com/questions/21608754/svg-text-alignment-issues-with-a-curved-textpath

In Firefox, the rendering is fine, without any issues to me. I can't find any compination of text-rendering and font-family which always results in a proper rendering in chrome.

![grafik](https://user-images.githubusercontent.com/564393/173902491-49a923f1-df2c-4ec7-9949-baebcc97997c.png)

**Comment by magicsunday** [comment]
I created an issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1407504

**Comment by magicsunday** [comment]
It has been fixed in Chrome v124. Now the underlines look nice and smooth here too.
